# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 691bae86e9bcaf58756ba2a11d7925093490a55af9a3fd0db4fca0fe11de6b546ab106f45fa5a8e84f7c2c1ca2c8f6994e588517c4cfa7b6720df9c7e488eae1

test:
  secret_key_base: c11b48f1bd580874a7a95adf35ba5dae35e0e0ef62b3ff56568b5d403c5fb1e6d3bc38dd5545e0b1d55a3812d58a1c1e35f2334c86713a85f2d58cdbc323c74c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
